#!/bin/sh
set -e

case "$1" in
	start)
		/usr/bin/aesdsocket-start-stop start

    ;;

	stop)
		/usr/bin/aesdsocket-start-stop stop


    ;;

    *)
		echo "Usage: aesdsocket {start|stop|restart|status}"
		exit 1
	;;


esac